### ISSUE TITLE
Working on PHP <7.0

### ISSUE THREAD

**Issue by ointeractive-depot** [Sektorka/php-win32std#1]
Hello! I'm trying to compile the ancient embeder which is not compiling on PHP >7 (but compiled on 5.6 nice). It was so difficult to find the win32std, but I've found yours, and was so joyful to see it, but of course I couldn't compile it at my PHP 5.6. Have many errors like this:

```
win32std.c
c:\php\sdk\phpdev\vc11\x86\pecl\win32std-1.1\php_win32std.h(59) : error C2143: синтаксическая ошибка: отсутствие ")" перед "*"
c:\php\sdk\phpdev\vc11\x86\pecl\win32std-1.1\php_win32std.h(59) : error C2143: синтаксическая ошибка: отсутствие "{" перед "*"
c:\php\sdk\phpdev\vc11\x86\pecl\win32std-1.1\php_win32std.h(59) : error C2059: синтаксическая ошибка: тип
c:\php\sdk\phpdev\vc11\x86\pecl\win32std-1.1\php_win32std.h(59) : error C2059: синтаксическая ошибка: )
c:\php\sdk\phpdev\vc11\x86\pecl\win32std-1.1\php_win32std.h(86) : error C2143: синтаксическая ошибка: отсутствие ")" перед "*"
c:\php\sdk\phpdev\vc11\x86\pecl\win32std-1.1\php_win32std.h(86) : error C2143: синтаксическая ошибка: отсутствие "{" перед "*"
c:\php\sdk\phpdev\vc11\x86\pecl\win32std-1.1\php_win32std.h(86) : error C2059: синтаксическая ошибка: тип
c:\php\sdk\phpdev\vc11\x86\pecl\win32std-1.1\php_win32std.h(86) : error C2059: синтаксическая ошибка: )
..\pecl\win32std-1.1\win32std.c(26) : fatal error C1083: Не удается открыть файл включение: ext/standard/php_smart_string.h: No such file or directory
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\cl.exe" : возвращенный код "0x2"
Stop.
```

Unfortunately I can't use PHP 7 and newer( Any help would be appreciated. Thanks in advance!)

**Comment by ointeractive-depot** [comment]
Don't worry, I could compile my app on PHP7.
